"""Create all tables

Revision ID: 26e24938c75b
Revises: 
Create Date: 2021-04-24 14:43:41.613345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e24938c75b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=6), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('ccy_iso', sa.String(length=3), nullable=False),
    sa.Column('ccy_override', sa.String(length=6), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('allow_decimals', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uname'), 'users', ['uname'], unique=True)
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.Column('due', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gname', sa.String(length=64), nullable=True),
    sa.Column('gmail', sa.String(length=128), nullable=True),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('tmail', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_gmail'), 'social', ['gmail'], unique=True)
    op.create_index(op.f('ix_social_handle'), 'social', ['handle'], unique=True)
    op.create_index(op.f('ix_social_tmail'), 'social', ['tmail'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tagname', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('amount_str', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_table('expense_tags',
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_tags')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('tags')
    op.drop_index(op.f('ix_social_tmail'), table_name='social')
    op.drop_index(op.f('ix_social_handle'), table_name='social')
    op.drop_index(op.f('ix_social_gmail'), table_name='social')
    op.drop_table('social')
    op.drop_table('modes')
    op.drop_table('budget')
    op.drop_index(op.f('ix_users_uname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
