"""Added a compound index

Revision ID: 90a4d6b26af4
Revises: 0aac2d0a66e4
Create Date: 2021-06-26 06:18:23.038991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a4d6b26af4'
down_revision = '0aac2d0a66e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_updated_on', table_name='expenses')
    op.create_index('idx_expenses_date_updated_on', 'expenses', ['date', 'updated_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_date_updated_on', table_name='expenses')
    op.create_index('ix_expenses_updated_on', 'expenses', ['updated_on'], unique=False)
    # ### end Alembic commands ###
